version: '3.1'

services:

  db:
    container_name: my_database
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 228228228
      POSTGRES_DB: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    # image: chat-app-api:latest
    build:
      context: ./
      dockerfile: packages/api/Dockerfile
    container_name: api
    expose:
      - 5000
    depends_on:
      - db

  web:
    # image: chat-app-web:latest
    build:
      context: ./
      dockerfile: packages/web/Dockerfile
    container_name: web
    expose:
      - 3000
    depends_on:
      - api
    environment:
      - API_WS_URL=ws://localhost:5000/graphql