version: '3.1'

services:

  db:
    container_name: my_database
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 228228228
      POSTGRES_DB: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: ./
      dockerfile: packages/api/Dockerfile

    environment:
      API_PORT: 5000
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_HOST: db
      DB_PASSWORD: 228228228
      DB_DATABASE: admin

    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - db

  web:
    build:
      context: ./
      dockerfile: packages/web/Dockerfile
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - API_WS_URL=ws://localhost:5000/graphql