version: '3.1'

services:

  db:
    container_name: my_database
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 228228228
      POSTGRES_DB: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080